### ISSUE TITLE
YEPPP bitrot

### ISSUE THREAD

**Issue by brentp** [abyzovlab/CNVnator#102]
cnvnator fails with YEPPP is used because it still refers to `window` and `window_next` instead of `window_rd` and `window_aib`.

however, after fixing those, then cnvnator stalls (no cpu-usage and just hangs) when reaching the partition step.

what type of performance increase was there from YEPPP? 2X? 3X? 30%?

**Comment by abyzov** [comment]
Hi,
as far as I remember it was somewhere between 1.5-2X improvement. I don’t think I’ll be able to maintain it anytime soon. So, please compile without using that library.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745




On Feb 5, 2018, at 10:18 AM, Brent Pedersen <notifications@github.com<mailto:notifications@github.com>> wrote:


cnvnator fails with YEPPP is used because it still refers to window and window_next instead of window_rd and window_aib.

however, after fixing those, then cnvnator stalls (no cpu-usage and just hangs) when reaching the partition step.

what type of performance increase was there from YEPPP? 2X? 3X? 30%?

**Comment by brentp** [comment]
understood. thanks for letting me know.
