### ISSUE TITLE
Sequence length is different from expectation  for 'Chr......' (always 1 line difference)

### ISSUE THREAD

**Issue by TahPx** [abyzovlab/CNVnator#105]
Hi, 
I'm working on my first bioinformatics project. i'm looking for copy number variations between the two plant species _Arabidopsis thaliana_ and _Arabidopsis halleri_.
I used BWA MEM for mapping A.halleri reads on the tair 10 Arabidopsis thaliana rev genom.
Now i started to work with CNVnator but i can't create a histogram.

```
/../src/cnvnator -root L70test.out.root -genome ATH-rev.fa -chrom Chr1 Chr2 -tree L70test.bam
/../src/cnvnator -genome ATH-rev.fa -root L70test.out.root -chrom Chr1 Chr2 -his 100
```

Allocating memory ...
Done.
Calculating histograms with bin size of 100 for 'Chr1' ...
Making GC histogram for 'Chr1' ...
Sequence length (**30427672**) is different from expectation (**30427671**) for 'Chr1'.
Doing nothing!
Done.
Calculating histograms with bin size of 100 for 'Chr2' ...
Making GC histogram for 'Chr2' ...
Sequence length (**19698290**) is different from expectation (**19698289**) for 'Chr2'.
Doing nothing!
Done.

As you can see the chromosome fasta files are always 1 line (sequence) longer than in the original sam header.
@SQ	SN:Chr1	LN:**30427671**
@SQ	SN:Chr2	LN:**19698289**
@SQ	SN:Chr3	LN:23459830
@SQ	SN:Chr4	LN:18585056
@SQ	SN:Chr5	LN:26975502
@SQ	SN:ChrM	LN:366924
@SQ	SN:ChrC	LN:154478

I extracted the chromosome reads from the already aligned L70test.bam file using Samtools
```
samtools view -h L70test.bam chr1 > L70test.chr1.sam
samtools view -bS L70test.chr1.sam > L70test.chr1.bam
samtools fasta L70test.chr1.bam > L70test.chr1.fa
```
My chromosome fasta files look like this. and i cant find anything unusual at the beginning or end of the files.
>HWI-D00473:179:H3KJKBCXX:1:1214:18900:63489/1
TAAAGAAGAAAATACATTCATGTATCTCCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACGTTTGATGATTTTAGGATGATTTGGGTTTAATGGGCTGTAGCTTAGTTTAAAAACAAATTGGCCCAATTACACATAATGAAATTAGGGTGTTACAATGGTGTTTTCTCCAACCGAATGGCCAGCGTTTTCAGTGTACTTGGAGGAATTTCAGAGCGAT
>HWI-D00473:179:H3KJKBCXX:1:1214:18900:63489/2
AAAAGACCCAAAATTTTTTTAAAAAAAAATTTACTAAGAGAATTTTAATTTTTTTTAGTTTTGCCATAGGTCTCATTATATATTGAGACGGTACACCTTCCTCATATTCTTGACAAACATCTCGAACTTAGCCTTGATTTCACTTATGAATTATTATAAGAAGAAATGTTAAAGTAAAGTAAAAA

I have the same problem when i use other libraries 
Can't find a workaround. It looks like some people have had the same problem, but could not find (or post) a solution.
i don't think its a windows/Unix convertion problem. (i use Ubuntu 16.04)
Editing the original samheader didn't work for me.
i hope someone here can help me to fix the problem

**Comment by abyzov** [comment]
Hi,
when creating histogram you don’t need -genome option, but you do need to have .fa file for each chromosome. With option -d you can specify a dir for those files.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by ggstatgen** [comment]
Hello OP,

I'm experiencing the same issue. Did you find a fix? Thanks!

**Comment by abyzov** [comment]
Hi,
please have .fa file for each chromosome and CNVnator should work.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by leahjm** [comment]
Hi OP,

I'm having this same issue. I'm also converting my bam file to .fa using the samtools fasta command. I think the problem might be that coordinates in bam files are 0-based where sam format is 1-based. This is why the sequence lengths are 1 bp off.

Have you found a solution yet? Perhaps a way to convert to fa without samtools? Thanks-

**Comment by abyzov** [comment]
Hi,
0-based or 1-based shouldn’t matter as the software compares length.
I believe an easier way is to download the reference genome and split into chromosomes, rather than converting bam to fa.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by AJ2802** [comment]
Hello,
I also encounter the problem that Sequence length is different from expectation by 1 when I run /home/CNVnator/./cnvnator -root out.root -chrom 1 -his 100 .
I am not sure the problem comes from bam file or fasta file.

**Comment by abyzov** [comment]
Hi,
most likely the issues is in .fa file. Please make sure that sequence in the .fa files is of correct length. Sometimes the sequence is different because of end-of-line character being treated differently on Mac/Unix and Windows.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by mjb400** [comment]
Hi,
Has anyone been able to find a solution for this issue?  I am having the exact same problem.  I am running cnvnator with the hg19 genome downloaded directly from ucsc, so there should be no issues with the fasta file itself.  Specifically, I'm using chr16 as reference, and when using "cnvnator -root out.root -chrom chr16 -his 100 -d /Path_to_reference_fa" I get the message that my reference is exactly one bp too long.  This issue is replicated on other chromosomes as well. So far I've tried:
-using the precut hg19 chr16 fasta file (downloaded from ucsc) as reference
-cutting the hg19 whole genome fasta file (downloaded from ucsc) into individual chromosomes (1-22, X, and Y) and using the path to the directory containing all of them as reference
-using the hg19 whole genome fasta file as reference (without being cut)
-I checked to make sure the reference fasta files were in unix format (dos2unix command as well as vim "set ff=unix")
-cutting the length of the reference fasta file, which resulted in the same error
-using hg19 from a different source (ncbi)

If anyone found a solution that worked for them, please share:) Thanks.

**Comment by abyzov** [comment]
Hello,
not sure what is going on. I've just downloaded chr16 sequence from UCSC genome browser and see that the length is 90354753 (see below), the same as have in files I got from other sources. Both sequencing work fine with my local copy of CNVnator that was just updated from github.

Do you get the same output for downloaded chromosome?

[abyzov@ Downloads]$ grep -v "^>" chr16.fa | wc
 1807096 1807096 92161849

[abyzov@ Downloads]$ calc
92161849 - 1807096
90354753

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by Firu-code** [comment]
I'm using genome file to generate root file using tree command on bam file. It generated around 700 kb root file.
Next I'm trying to assess read depth using his command with a window of 1000.
It says 

chromosome/contig information parsed.
Sequence length (0) is different from expectation (202105980) for 'NC_037545.1'.

Doing nothing.

The problem remains even if i use -chrom in command and have the fasta file of that chr in directory as well as in command line with -d option.

Kind help is requested.

**Comment by abyzov** [comment]
Hi,
it looks like sequence of the contig can’t be parsed.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Quantitative Health Sciences,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 7-91
Rochester, MN 55905
www.abyzovlab.org
tel: +1-(507)-538-0978

On Feb 2, 2023, at 10:04 PM, Firu-code ***@***.***> wrote:



I'm using genome file to generate root file using tree command on bam file. It generated around 700 kb root file.
Next I'm trying to assess read depth using his command with a window of 1000.
It says

chromosome/contig information parsed.
Sequence length (0) is different from expectation (202105980) for 'NC_037545.1'.

Doing nothing.

The problem remains even if i use -chrom in command and have the fasta file of that chr in directory as well as in command line with -d option.

Kind help is requested.
