### ISSUE TITLE
CNVnator genotype command output

### ISSUE THREAD

**Issue by ghost** [abyzovlab/CNVnator#113]
Hi,

What does the output of this CNVnator command means:

`./cnvnator -root my.root -genotype 100 -ngc`

Genotype chr1:16151901-16155600

Genotype chr1:16151901-16155600 my.root 0.979948 -1

What does the value means?

Thanks,

Waqas.

**Comment by abyzov** [comment]
Hi,
the second to last value is estimated Copy Number from using coverage across you bin size (100 bp). The last number is estimated Copy Number from using coverage across 1000 bp bins. It is -1 because no histograms are calculated for that bin size in your file.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
