### ISSUE TITLE
Large RD values and GC correction errors

### ISSUE THREAD

**Issue by reddy25** [abyzovlab/CNVnator#116]
Hi, 
I was trying to run CNV analysis against the scaffolds and was getting few errors. the script i used:
cnvnator -genome ${ref}/scaffolds-M6.fasta -root sca.root -chrom scaffold_1 -tree 
 {bam}/unmapped.sorted.bam -unique
cnvnator -root sca.root -chrom scaffold_1 -d ${ref} -his 100
cnvnator -root sca.root -chrom scaffold_1 -stat 100
cnvnator -root sca.root -chrom scaffold_1 -partition 100
cnvnator -root sca.root -chrom scaffold_1 -call 100 > sca_cnv.out

1) Correcting counts by GC-content for 'scaffold_1' ...
Zero value of GC average.
Bin 1219 with center 121850 is not corrected.
Zero value of GC average.
Bin 1371 with center 137050 is not corrected.
Zero value of GC average.
Bin 3138 with center 313750 is not corrected.
Zero value of GC average.
Bin 4421 with center 442050 is not corrected.
Zero value of GC average.
Bin 4556 with center 455550 is not corrected.
Zero value of GC average.
Bin 4778 with center 477750 is not corrected.
Zero value of GC average.
Bin 5363 with center 536250 is not corrected.
Zero value of GC average.
Bin 6531 with center 653050 is not corrected.
Zero value of GC average.
Bin 6605 with center 660450 is not corrected.
Zero value of GC average.
Bin 7589 with center 758850 is not corrected.
Zero value of GC average.
Bin 7753 with center 775250 is not corrected.
Zero value of GC average.
Bin 7871 with center 787050 is not corrected.
Zero value of GC average.

is this normal ?

2) And the output was 
duplication     scaffold_1:1-3893100    3.8931e+06      419438  0       0       0       0       0.447725
Normalised RD value was too large and i was getting all  zero evalues. 

3) And also, for some other scaffolds i was getting some abnormal ranges like this 
Partitioning RD signal for 'scaffold_728' with bin size of 100 ...
Average RD per bin is 0 +- 1.76561
Bin band is 2
Abnormal range (3, 2)
Abnormal range (4, 3)
Abnormal range (5, 4)
Abnormal range (6, 5)
Abnormal range (7, 6)
Abnormal range (8, 7)
Abnormal range (9, 8)
Abnormal range (11, 10)

Could you please look into my issue and tell me what might possibly gone wrong. 
Thank you!!

**Comment by abyzov** [comment]
Hi,

1) Yes that happens sometime. Usually, not a big deal. But you may want to increase bin size.
2) Could be fine depending on what was the average RD across genome. You can visualize the region and check whether you think the call was correct.
3) This is a obvious problem. Average RD was not determined correct "0 +- 1.76561”. It is either because bin size is too small, or scaffold is too short (if you are running CNVnator per scaffold).

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745




On Jun 5, 2018, at 11:05 AM, reddy25 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
I was trying to run CNV analysis against the scaffolds and was getting few errors. the script i used:
cnvnator -genome ${ref}/scaffolds-M6.fasta -root sca.root -chrom scaffold_1 -tree
{bam}/unmapped.sorted.bam -unique
cnvnator -root sca.root -chrom scaffold_1 -d ${ref} -his 100
cnvnator -root sca.root -chrom scaffold_1 -stat 100
cnvnator -root sca.root -chrom scaffold_1 -partition 100
cnvnator -root sca.root -chrom scaffold_1 -call 100 > sca_cnv.out

  1.  Correcting counts by GC-content for 'scaffold_1' ...
Zero value of GC average.
Bin 1219 with center 121850 is not corrected.
Zero value of GC average.
Bin 1371 with center 137050 is not corrected.
Zero value of GC average.
Bin 3138 with center 313750 is not corrected.
Zero value of GC average.
Bin 4421 with center 442050 is not corrected.
Zero value of GC average.
Bin 4556 with center 455550 is not corrected.
Zero value of GC average.
Bin 4778 with center 477750 is not corrected.
Zero value of GC average.
Bin 5363 with center 536250 is not corrected.
Zero value of GC average.
Bin 6531 with center 653050 is not corrected.
Zero value of GC average.
Bin 6605 with center 660450 is not corrected.
Zero value of GC average.
Bin 7589 with center 758850 is not corrected.
Zero value of GC average.
Bin 7753 with center 775250 is not corrected.
Zero value of GC average.
Bin 7871 with center 787050 is not corrected.
Zero value of GC average.

is this normal ?

  1.  And the output was
duplication scaffold_1:1-3893100 3.8931e+06 419438 0 0 0 0 0.447725
Normalised RD value was too large and i was getting all zero evalues.

  2.  And also, for some other scaffolds i was getting some abnormal ranges like this
Partitioning RD signal for 'scaffold_728' with bin size of 100 ...
Average RD per bin is 0 +- 1.76561
Bin band is 2
Abnormal range (3, 2)
Abnormal range (4, 3)
Abnormal range (5, 4)
Abnormal range (6, 5)
Abnormal range (7, 6)
Abnormal range (8, 7)
Abnormal range (9, 8)
Abnormal range (11, 10)

Could you please look into my issue and tell me what might possibly gone wrong.
Thank you!!
