### ISSUE TITLE
can't run CNVnator

### ISSUE THREAD

**Issue by xgdong** [abyzovlab/CNVnator#117]
Hi,Dr. Abyzov, I think I installed CNVnator_v0.3.3 successfully, but it doesn't run well, as the command and message below: 
cnvnator -root JY1.root -chrom 1 -tree JY1.sorted.markdup.bam
cnvnator: Symbol `_ZTV12TStringToken' has different size in shared object, consider re-linking
cnvnator: Symbol `_ZTV6TNamed' has different size in shared object, consider re-linking
...
 what does 'cnvnator: Symbol `_ZTV12TStringToken' ...' mean? 
Thank you!
Steph

**Comment by abyzov** [comment]
Hi,
I don’t have such symbol in the code. I believe it is something internal to compiler. I suspect that the error is because of using different compilers to compile ROOT and CNVnator.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by xgdong** [comment]
Yes,I finally found the issue, It runs smoothly after I set the root path. Thanks for replying.
