### ISSUE TITLE
CNVnator partition step - %cpu issue

### ISSUE THREAD

**Issue by hoonghim** [abyzovlab/CNVnator#132]
Dear professor Abyzov,

Hello, I'm using CNVnator to calculate copy number alterations in normal WGS data.

I am analyzing more than 1,000 samples in linux server (CPU core: 144).

When I run CNVnator partition step, load average (sum of %cpu) is going up to 600 or more.

Is there any way to manually set CPU usage in partitioning step?

I am afraid that too much CPU usage will bring down the server.

Thank you for your time. 

If you give me the answer, it will be very helpful for the analysis.

Sincerely,

Seung-hoon

**Comment by abyzov** [comment]
Hi,
job schedulers allow to specify how many CPU are given to a submitted a job. So, using a scheduler could be an options.
Otherwise you can compile CNVnator with OMP off, i.e., 'make OMP=no’. Such executable will always use only 1 CPU.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by hoonghim** [comment]
Thank you for your quick response.

When I used Sungrid qsub and specify cpu cores using -pe smp option, it didn't work. (Maybe there was another way to set CPU cores, but I don't known)

I followed your advice, 'make OMP=no’ when compiling CNVnator, and it works!

Thank you for your help!

Cheers,

Seung-hoon




> Hi, job schedulers allow to specify how many CPU are given to a submitted a job. So, using a scheduler could be an options. Otherwise you can compile CNVnator with OMP off, i.e., 'make OMP=no’. Such executable will always use only 1 CPU. Alexej Abyzov, Ph.D. Senior Associate Consultant, Assistant Professor of Biomedical Informatics, Department of Health Sciences Research, Center for Individualized Medicine, Mayo Clinic ----------------------------- Mayo Clinic, 200 1st street SW, Harwick 3-12 Rochester, MN 55905 [www.abyzovlab.org<http://www.abyzovlab.org](http://www.abyzovlab.org<http://www.abyzovlab.org)> tel: +1-(507)-538-0978 fax: +1-(507)-284-0745
