### ISSUE TITLE
how to increase the ratio of average of RD signal to std dev 

### ISSUE THREAD

**Issue by likexin323** [abyzovlab/CNVnator#146]
Hi Dr. Abyzov,

       We are trying to detect CNV from NGS data (PE150), and the sequencing depth for each individual is from 11X to 20x. We tried the bin size from 100 to 10000, however, we didn't get a  ratio of average of RD signal to std dev ranging between 4 and 5, and it is alway around 3. Could you please give me some idea how to improve my analyses and increase this ratio?

Whether the bandwidth should  be set manually in order to increase this ratio?

Thank you in anticipation!

Best,

Li

**Comment by likexin323** [comment]
Hi Dr. Abyzov,

We  are trying to detect CNV from NGS data (PE150) using CNVnaor, and the sequencing depth for each individual is from 11X to 20x. We tried the bin size from 100 to 10000, however, we didn't get a  ratio of average of RD signal to std dev ranging between 4 and 5, and it is alway around 3. Could you please give me some idea how to improve my analyses and increase this ratio?Whether the bandwidth should be set manually in order to increase this ratio?

Thank you in anticipation!

Best,

Li

**Comment by abyzov** [comment]
Hi
you may be dealing with an intrinsically noisy sample due to degraded DNA, amplification during lib-prep, bad sequencing run, etc.

Try to visualize coverage -view option.
In the recent version there is undocument function ‘gview’, which can give a global view of coverage across genome.

Example,
cnvnator -root your.root -view your_bin
> gview


Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
