### ISSUE TITLE
plotrdbaf.py: invalid value encountered in double_scalars

### ISSUE THREAD

**Issue by gevro** [abyzovlab/CNVnator#193]
Hi,
plotrdbaf.py is giving this warning/error:
/home/dnanexus/CNVnator/plotrdbaf.py:142: RuntimeWarning: invalid value encountered in double_scalars
  ng2.append(1.0*m[i][res/2]/m1)

**Comment by gevro** [comment]
Note this seems to happen or not happen depending on the combination of bins, rdbs, and res values. Specifically, it seems to be triggered when bins and res options are lower.

**Comment by gevro** [comment]
This is the last remaining issue I have. Any suggestions for this?

**Comment by suvakov** [comment]
Does it affect resulting plot? It looks like division by zero when bin is out of SNPa but I am not sure. Btw, we have continued to develop such plot tools as a part of CNVpytor: https://github.com/abyzovlab/CNVpytor
We just released first version with almost all CNVnator features implemented.

**Comment by gevro** [comment]
Plot looks fine despite this issue. Could it be that bin size is too small? 
--> What is the recommended RD bin size and BAF bin size for standard whole-genome sequencing (~30-40x coverage)?

Thanks, I will try your new package! Please see my other open issues for some other questions.

**Comment by suvakov** [comment]
This warning is not important because bins without data would not be plotted anyway. Even with large bin size some bins would be without SNPs. However, we should catch this exception because it could be confusing for users. Thanks.

We expect one SNP in around 1000bp, so recommended bin size is at least 10k. Increasing bin size will reduce noise but smaller events will not be visible. If you want to see larger events with small frequency you should use larger bin size. Opposite, for smaller events with higher frequency use smaller bins. For RD you can go below 1000 but for this whole-chromosome or whole-genome plots I recommend same bin size as used for SNP-s.
