### ISSUE TITLE
-his step takes too long

### ISSUE THREAD

**Issue by MaoSihong** [abyzovlab/CNVnator#202]
how does it possible to costs more than 2000min when I run the -his 100 step with the command like: cnvnator -root xx.root -his 100 -fasta xxxx_1.fq.gz xxxx_2.fq.gz
what's wrong?

**Comment by abyzov** [comment]
Hi,
CNVnator does not work with .fastq files. You have to use bams. For the reference genome you have to use .fa file.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by MaoSihong** [comment]
but I've also tried *.fa.gz *.fasta format as the input of the individual seq data,
It seems to have the same question, and sometimes the process announces "core dump"

**Comment by abyzov** [comment]
Could you please send the exact command you used and the output that you got.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by MaoSihong** [comment]
well, the command I used comes as follows:
cnvnator -root pad01-a.root -tree pad01-a.bam
cnvnator -root pad01-a.root -his 100 -fasta pad01-a.fa.gz
#however the *.fa.gz file was converted from the consistent bamfile since I only got individual seqs #like pad01-a_1.fq.gz & pad01-a_2.fq.gz. I thought it which could be the main problem?
cnvnator -root pad01-a.root -stat 100
cnvnator -root pad01-a.root -partition 100
cnvnator -root pad01-a.root -call 100 > pad01-a.bed

I also make the vcf output without importing any SNPs yet.
The attachment file will be sent via the email.
exp your reply!

**Comment by MaoSihong** [comment]
Here are the files I got.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"abyzov"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月6日(星期一) 中午1:26
收件人:&nbsp;"abyzovlab/CNVnator"<CNVnator@noreply.github.com&gt;;
抄送:&nbsp;"毛思闳"<839673804@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [abyzovlab/CNVnator] -his step takes too long (#202)





 Could you please send the exact command you used and the output that you got.
 
 Alexej Abyzov, Ph.D.
 Senior Associate Consultant,
 Assistant Professor of Biomedical Informatics,
 Department of Health Sciences Research,
 Center for Individualized Medicine, Mayo Clinic
 -----------------------------
 Mayo Clinic, 200 1st street SW, Harwick 3-12
 Rochester, MN 55905
 www.abyzovlab.org<http://www.abyzovlab.org&gt;
 tel: +1-(507)-538-0978
 fax: +1-(507)-284-0745
 
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

pad01-a.bed (1.34M, 2020年04月06日 16:18 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=793433664ce7dbcdf5533f541064031d0e070a075252075314560752014905055c521e045357521f0a0703560653060000025157366f3142585003571b051f505c503320&code=943f6d12




pad01-a.root (156.46M, 2020年04月20日 16:18 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=746434655c905bc1f903385715325118065104570550520718510c57511f57020d021907070a001a05010106050a5a0507575103333e6347540004541e534d455a0b406575&code=5d4e32c7




pda09-a.vcf (2.55M, 2020年04月06日 16:19 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=74323031fb0ee1cef8553c031035041e5202060853530e53190405070518020455051d505207051c555453505701005207545553363e3641505300081b54184757543077&code=42016561

**Comment by abyzov** [comment]
Hi,
not sure that is the problem because there is not error message.
Please make sure that sequences in .fa.gz file are not in one line. This line can get very long and internal buffer may be be overflown.

Also, it is not clear to me what you mean by “file was converted from the consistent bamfile”.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by MaoSihong** [comment]
with the word“file was converted from the consistent bamfile”, I mean that the individual seq file(*.fa.gz) I use was converted from the same bamfile via samtools, but not an origin .fa file.

**Comment by abyzov** [comment]
Hi,
first of all. I don’t think it is a good idea to reconstruct the reference sequence from bam. It could be incomplete or incorrect.
Second, I don’t know how the file is formatted but please make sure that sequence for chromosome is split across multiple lines rather than is in a single line.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by MaoSihong** [comment]
![image](https://user-images.githubusercontent.com/50494689/79633666-24775080-8199-11ea-955b-f46dcfce8ccb.png)
I think I‘ve made it right in -his step this time，but is there any problem according to the these notices above ？

**Comment by abyzov** [comment]
Hi,
according to the message files with chromosome sequence were not found.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
