### ISSUE TITLE
Bin size and sequence read length?

### ISSUE THREAD

**Issue by devin-qiu** [abyzovlab/CNVnator#270]
Hello Dr. Abyzov, 

Thank you for developing CNVnator! I have some questions regarding this software: 

1. Does the input bin-size need to be in concordance with the sequencing read length? For example, our 30x sequencing samples has read length of ~150bp, should we consider setting the bin_size as 150?

2. I already generated a CNV call set with our child's sequencing data in a trio. Since I also have data for parents, could we filter de novo CNV in proband rather than having a whole CNV calls, which might be from parents? 

3. The partitioning step is the most time consuming step, so we want to avoid running this step again if we keep the same input sequencing file and bin_size. I'm wondering if CNVnator generates an intermediate document of partitioned sequences? If so, where is it stored?

Looking forward to hearing from you, 
Devin

**Comment by abyzov** [comment]
Hi Devin,
below are answers to your questions.

1. Yes, the size of bins depends on coverage and read length. For you data I would consider bins between 200-500 bps.
2. Yes, you can genotype CNV region in parents and then compare genotype to call de novo CNVs. See Abyzov et al., Nature 2012 PMID:23160490
3. Yes, all the info (after each step) is store in .root file.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Quantitative Health Sciences,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978

On Aug 29, 2022, at 1:12 PM, andresqiu ***@***.******@***.***>> wrote:



Hello Dr. Abyzov,

Thank you for developing CNVnator! I have some questions regarding this software:

  1.  Does the input bin-size need to be in concordance with the sequencing read length? For example, our 30x sequencing samples has read length of ~150bp, should we consider setting the bin_size as 150?

  2.  I already generated a CNV call set with our child's sequencing data in a trio. Since I also have data for parents, could we filter de novo CNV in proband rather than having a whole CNV calls, which might be from parents?

  3.  The partitioning step is the most time consuming step, so we want to avoid running this step again if we keep the same input sequencing file and bin_size. I'm wondering if CNVnator generates an intermediate document of partitioned sequences? If so, where is it stored?

Looking forward to hearing from you,
Devin
