### ISSUE TITLE
Doc not enough

### ISSUE THREAD

**Issue by bkaan99** [abyzovlab/CNVnator#273]
Hello, I am doing research on **genome**. I am just learning about these topics. 

 think that the documentation of this tool is insufficient for the initial stage. 

Can you post a document that explains the explanations in more detail? 

For example, explaining the steps in the **workflow** in more detail..

**Comment by abyzov** [comment]
Hi,
we now recommend (https://github.com/abyzovlab/CNVpytor) to use CNVpytor instead of CNVnator.
Documentation for CNVpytor is more detailed.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Quantitative Health Sciences,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978

On Sep 30, 2022, at 4:00 AM, Bilge Kaan Gürgen ***@***.******@***.***>> wrote:



Hello, I am doing research on genome. I am just learning about these topics.

think that the documentation of this tool is insufficient for the initial stage.

Can you post a document that explains the explanations in more detail?

For example, explaining the steps in the workflow in more detail..

**Comment by bkaan99** [comment]
Thx!!
