### ISSUE TITLE
"Maximum buffer size exceeded"

### ISSUE THREAD

**Issue by AJ23ZX** [abyzovlab/CNVnator#53]
Hi,
I used CNVnator v_0.3 to call CNVs in our WGS data (7x). When I did the second step "CREATING A HISTOGRAM", I encounter a problem that said "Maximum buffer size exceeded". Does it have impact on the result? How can I deal with it? Thanks.

Here is the issue below:
[root@maize-1 bamtest]# cnvnator -genome /workdir/xz235/maize3.fa -root total.root -chrom 1 2 3 4 5 6 7 8 9 10 -his 500 -d /workdir/xz235/refSeqbyChr/
Warning in <UnknownClass::SetDisplay>: DISPLAY not set, setting it to xx.xxx.xx.xxx:0.0
Allocating memory ...
Done.
Calculating histograms with bin size of 500 for '1' ...
Making GC histogram for '1' ...
Maximum buffer size exceeded.

**Comment by AJ23ZX** [comment]
Can anybody help me?

**Comment by abyzov** [comment]
Hi,
this error occurs because the length of sequencing in FASTA file is longer then described in bam header.
Typically it happens because on Windows .txt files have additional end-of-line character, that inflates sequence length.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by AJ23ZX** [comment]
Yes, I updated my ROOT to 6.08.00 and CNVnator to 0.3.3. After that it game me a detail of what you said, so I modified the seq files under Linux and solved it. Thank you, someone misled me to allocate more memery to run CNVnator, so I was confusing.
