### ISSUE TITLE
Whole Genome Bisulfite Sequencing Compatability

### ISSUE THREAD

**Issue by tantrev** [abyzovlab/CNVnator#66]
Just wondering if CNVnator can be used on WGBS data, like the [readDepth](https://github.com/chrisamiller/readDepth) package.

**Comment by abyzov** [comment]
Hi,
I haven’t tested it on WGBS but guessing it should work. However, the performance could be degraded because of compromised read mapping.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by tantrev** [comment]
Sounds great, thank you!
