### ISSUE TITLE
Multiple bam CNV calling

### ISSUE THREAD

**Issue by guillaume-rs** [abyzovlab/CNVnator#71]
Hello,
I try to use CNVnator to call CNVs from several samples.
I made a test giving all the bam files at once, in the results I have a list of CNVs, but I don't know which one correspond to which sample.
Is it a feature present in CNVnator, and I've made a mistake? or should I run the program on each sample and cross the results? (I would like to compare reccurent CNVs between my samples)

Thank you in advance for your help.

Guillaume ROBERT

**Comment by abyzov** [comment]
Hi,
cnvnator can only call CNVs one sample at a time.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by Jordi-Valls** [comment]
Hi Alexej,

I just want to know if I use the merge option of CNVnator when I have the root of different samples this merge allow us to analyse  more samples at same time. If this is not true, what do exactly the merge option? is for a sample splited by different bams?

Thanks for your help

Jordi

**Comment by abyzov** [comment]
Yes, the option is for merging different .root files from different .bam files but for the same sample/individual.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by Jordi-V** [comment]
Hi Alexej,

thanks for your last reply, but I have a new question... Its about how you merge all samples ran by CNVnator in 1000 Genomes, in order to merge all the outputs.

Thanks for your help

Jordi

**Comment by abyzov** [comment]
Hi,
merging CNVs calls is not an easy and unsolved problem. I would advise to read about possible strategies in the two paper from SV group of the 1000 Genome project (both papers are in Nature).
Alternatively you can genotype (option -genotype) all calls across all samples.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by Jordi-V** [comment]
Hi Alexej,

I read the supplementary information of 1000 Genome papers, and I only found this... "We merged
CNV calls for individuals within each population. For CNVnator site merging we initially clustered confident overlapping calls and averaged coordinates of each bound, pursuing the merging initially by population and then across the entire sample set." This work was done by  Mark Gerstein and you, so could you tell me which scripts do you use for this prupose?? because how you find the confident overlapping?? and how you generate the averaged coordinates??

On the other hand, If I use the option -genotype of CNVnator tool, only for one sample the program is still run during more 15 hours... and no ending... So I have to cut all the genome of my samples by batches and how can I entry this batches (sorry but in github for me is not very clear, could you give me som example??)?? How can I run the genotype command using multiple samples?? like this??

cnvnator -root sample1.root sample2.root .... -genotype 150

Finally my samples are sequenced at 30X and the read length is 150. So to better detection of CNV I should use a bin size like my read length?? or should be other size??

Thanks for your help

**Comment by abyzov** [comment]
Hi,
sorry, don’t know where the script is. As far as I remember calls were merged if they overlap reciprocally by 50%. Then for each pair of calls we average starts and average ends.

This is how you can genotype multiple CNVs per sample

awk '{ print $2 } END { print "exit" }' calls.cnvnator | ./cnvnator -root NA12878.root -genotype 100

To genotype across multiple samples you have to run the command for each sample.

You should use bin size which give average RD per bin roughly 4-5 times large than standard deviation of RD.
Use command -eval for evaluations.


Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

On Nov 21, 2018, at 4:44 AM, Jordi Valls Margarit <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Alexej,

I read the supplementary information of 1000 Genome papers, and I only found this... "We merged
CNV calls for individuals within each population. For CNVnator site merging we initially clustered confident overlapping calls and averaged coordinates of each bound, pursuing the merging initially by population and then across the entire sample set." This work was done by Mark Gerstein and you, so could you tell me which scripts do you use for this prupose?? because how you find the confident overlapping?? and how you generate the averaged coordinates??

On the other hand, If I use the option -genotype of CNVnator tool, only for one sample the program is still run during more 15 hours... and no ending... So I have to cut all the genome of my samples by batches and how can I entry this batches (sorry but in github for me is not very clear, could you give me som example??)?? How can I run the genotype command using multiple samples?? like this??

cnvnator -root sample1.root sample2.root .... -genotype 150

Finally my samples are sequenced at 30X and the read length is 150. So to better detection of CNV I should use a bin size like my read length?? or should be other size??

Thanks for your help

**Comment by Jordi-V** [comment]
Hi  Alexej,

thanks a lot for your reply, I will genotype sample by sample, because If I understand well (correct me if I'm wrong) there's no option to genotype al samples together. using CNVnator?

Thanks again for your time and response.

Best regards

Jordi

**Comment by abyzov** [comment]
Currently there is no such capability.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by Jordi-V** [comment]
Thanks Alexej,

I'm apologise for too much questions... But I tried to genotype my ouputs and I get these results in my error file:
Can't find directory 'bin_1000'.

the command used to genotype:
awk '{ print $2 } END { print "exit" }' file.call | cnvnator -root sample.root -genotype 150

my output file I found this:

Genotype 1:11551-14400 sample.root 6.29541 -1
Genotype 1:16201-18750 sample.root 7.9896 -1
Genotype 1:24301-30900 sample.root 3.36389 -1
Genotype 1:32551-36150 sample.root 4.08275 -1
Genotype 1:58351-62250 sample.root 3.03553 -1

This information is taked from calling output step:

duplication    1:11551-14400 2850    3.14858 1.62129e-05     1.04922e-95     4646.14 8.3925e-36      1
duplication     1:16201-18750   2550    3.99596 0.0123463       3.02568e-217    8241.98 0       1
duplication     1:24301-30900   6600    1.68232 0.00118432      2.50779e+09     16.0229 2.61807e+09     1
duplication     1:32551-36150   3600    2.04212 0.011288        2.80925e+09     1.47178 5.82884e-34     1
duplication     1:58351-62250   3900    1.51813 0.0122498       2.018e+09       15.5862 8080.68 1

So... I dont underestand the output of genotyping... How can I get this output in vcf format?? 0/0, 0/1 1/1??

Is correct the output obtained??
Thanks again

Jordi

**Comment by abyzov** [comment]
Hi,
the out is estimated CN for each regions. The estimates is done twice: for the bins size your provided and for 1000 bp bins (default hardcoded). If you don’t have histograms for 1000 bp bins then you get error message and -1 at the end of each line.

It is up to you have to treat the estimates. You can round it off to nearest integer to assign genotype.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

On Dec 4, 2018, at 3:45 AM, Jordi Valls Margarit <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks Alexej,

I'm apologise for too much questions... But I tried to genotype my ouputs and I get these results in my error file:
Can't find directory 'bin_1000'.

the command used to genotype:
awk '{ print $2 } END { print "exit" }' file.call | cnvnator -root sample.root -genotype 150

my output file I found this:

Genotype 1:11551-14400 sample.root 6.29541 -1
Genotype 1:16201-18750 sample.root 7.9896 -1
Genotype 1:24301-30900 sample.root 3.36389 -1
Genotype 1:32551-36150 sample.root 4.08275 -1
Genotype 1:58351-62250 sample.root 3.03553 -1

This information is taked from calling output step:

duplication 1:11551-14400 2850 3.14858 1.62129e-05 1.04922e-95 4646.14 8.3925e-36 1
duplication 1:16201-18750 2550 3.99596 0.0123463 3.02568e-217 8241.98 0 1
duplication 1:24301-30900 6600 1.68232 0.00118432 2.50779e+09 16.0229 2.61807e+09 1
duplication 1:32551-36150 3600 2.04212 0.011288 2.80925e+09 1.47178 5.82884e-34 1
duplication 1:58351-62250 3900 1.51813 0.0122498 2.018e+09 15.5862 8080.68 1

So... I dont underestand the output of genotyping... How can I get this output in vcf format?? 0/0, 0/1 1/1??

Is correct the output obtained??
Thanks again

Jordi

**Comment by MaoSihong** [comment]
![image](https://user-images.githubusercontent.com/50494689/92552342-01a61f80-f293-11ea-80fc-788844df3112.png)
hello ，I also met the problem that cannot find the dir bin_1000. how can I fix it or it just can be omitted?

**Comment by abyzov** [comment]
Hi,
this message does not affect performance.
To eliminate it you should complete -his 1000 and -stat 1000 steps.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by MaoSihong** [comment]
> Hi, this message does not affect performance. To eliminate it you should complete -his 1000 and -stat 1000 steps. Alexej Abyzov, Ph.D. Senior Associate Consultant, Associate Professor of Biomedical Informatics, Department of Health Sciences Research, Center for Individualized Medicine, Mayo Clinic ----------------------------- Mayo Clinic, 200 1st street SW, Harwick 3-12 Rochester, MN 55905 [www.abyzovlab.org<http://www.abyzovlab.org](http://www.abyzovlab.org<http://www.abyzovlab.org)> tel: +1-(507)-538-0978 fax: +1-(507)-284-0745

I saw the past reply that you said we can round the CN off to the nearest integer to assign the genotype. could you please give me an example about how can I generate an genotype lable like 0/0,0/1,1/1 or others from the CN float value I got by the command as "awk '{ print $2 } END { print "exit" }' file.call | cnvnator -root sample.root -genotype 500"
THANKS A LOT!

**Comment by abyzov** [comment]
Hi,
for diploid chromosomes genotype < 0.5 is 1/1, for 0.5 < genotype < 1.5 is 0/1, and for 1.5 < genotype < 2.5 is 0/0, etc.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by MaoSihong** [comment]
here genotype means CN or something else？if so，how about duplications with high CN？



发自我的iPhone


------------------ Original ------------------

**Comment by abyzov** [comment]
Here CN mean estimated copy number.
Genotype for high copy number can’t be determined from just RD alone.  For example, CN ~=5 can be 0/5, 1/4, 2/3.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by MaoSihong** [comment]
well, so we should&nbsp;regard GT:CN in vcf
File as CN/CN’:(CN+CN’) but not simply ref/alt:CN,right?



发自我的iPhone


------------------ Original ------------------

**Comment by abyzov** [comment]
Sorry, if my previous email was confusing.

In VCF format you’ll need to define haplotypes first (0 haplotype is the reference) and then refer to these definitions from genotype field.

See https://www.biostars.org/p/232205/

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Associate Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, 200 1st street SW, Harwick 3-12
Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

On Sep 20, 2020, at 3:18 AM, MaoSihong <notifications@github.com<mailto:notifications@github.com>> wrote:


well, so we should&nbsp;regard GT:CN in vcf
File as CN/CN’:(CN+CN’) but not simply ref/alt:CN,right?



发自我的iPhone


------------------ Original ------------------
