### ISSUE TITLE
Build custom genomes?

### ISSUE THREAD

**Issue by sklages** [abyzovlab/CNVnator#75]
Hi,

is there a way to use other genomes for analysis? E.g. mm10 or whatever?

thanks,
Sven

**Comment by abyzov** [comment]
Sure, as long as genome is described in the bam header.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by lixin4306ren** [comment]
Hi, Alexej

Could you say more specific? I want to run CNVnator on chicken genome (galgal4). How should I build chicken genome for CNVnator? Thanks.

Xin

**Comment by abyzov** [comment]
As long as your bam has description of chromosome CNVnator will work.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by CBorreda** [comment]
Hello Alexej

I am running CNVnator and I found a similar issue. My BAM files have chromosome length in the header, as shown below:
@SQ     SN:scaffold_1   LN:28940638
@SQ     SN:scaffold_2   LN:36376123
@SQ     SN:scaffold_3   LN:51050279
@SQ     SN:scaffold_4   LN:25649528
@SQ     SN:scaffold_5   LN:43300495
...etc

Is this the proper formatting? The questions come because, after generating the stats (./cnvnator -root file.root [-chrom name1 ...] -stat bin_size) I got this:

Average RD per bin (1-22) is 58.6299 +- 19.3199 (after GC correction)
Average RD per bin (X,Y)  is 0 +- 0 (after GC correction)

While my data doesn't have X or Y chromosome. Also, there are more than 22 scaffolds, up to 2533. Is this just a default comment or is CNVnator actually considering my data to have 22 chromosomes + XX/XY?

**Comment by abyzov** [comment]
Hi,
yes since you have not X&Y depth of coverage for these chroms is 0. All other contigs are considered for 1-22 output.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
