### ISSUE TITLE
What does a genotype result of -1 mean?

### ISSUE THREAD

**Issue by ernfrid** [abyzovlab/CNVnator#83]
When using cnvnator to gentoype a region, we occasionally observe that it returns a copynumber value of -1.

I think that this is due to these lines: https://github.com/abyzovlab/CNVnator/blob/9d3a92b01ce4f554227b566e4c9b8ba8af42d0af/Genotyper.cpp#L84-L90

How should this -1 value be interpreted? Does it mean that the copy number simply can't be determined for that window and should be treated as a missing or null value?

**Comment by abyzov** [comment]
Yes, -1 would mean that genotype couldn’t be determined for some reason.
Not sure why you see it occasionally. From those line I feel that it would return -1 for all CNV on a chromosome or for all CNVs. Sporadic behavior wouldn’t be expected.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745



On Oct 6, 2017, at 8:03 AM, Dave Larson <notifications@github.com<mailto:notifications@github.com>> wrote:


When using cnvnator to gentoype a region, we occasionally observe that it returns a copynumber value of -1.

I think that this is due to these lines: https://github.com/abyzovlab/CNVnator/blob/9d3a92b01ce4f554227b566e4c9b8ba8af42d0af/Genotyper.cpp#L84-L90

How should this -1 value be interpreted? Does it mean that the copy number simply can't be determined for that window and should be treated as a missing or null value?

**Comment by ernfrid** [comment]
Thank you for clarifying. 

It's definitely sporadic sample to sample (some samples have -1, but most do not). I'll have to check to see if we're seeing it on entire chromosomes or only single sites though.

**Comment by ernfrid** [comment]
So I checked and, as you stated, the -1 value appears for an entire chromosome in the case I checked.

What are the causes for this to happen? In general, we have high coverage genomes and I wouldn't expect we'd have insufficient coverage for genotyping of a chromosome.

**Comment by abyzov** [comment]
Dave,
this would require debugging. My guess is that something goes wrong with determining mean of RD distribution.
It could be that bin size is too small or the distribution has a weird shape.
You can open .root file manually using TBrowser object in ROOT, then go to a directory for you bin size (e.g., bin_300), and then find histograms rd_p_300 or rd_p_xy_300. By clicking on the histograms you can visualized the distribution and then fit with gaussian function.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by ernfrid** [comment]
It has taken me quite a while to get around to looking at this, but you are correct. The histograms show the read depth distribution to have a very strong right tail. Fitting a Gaussian to the histogram seems to result in just the right tail of the gaussian visible.

**Comment by abyzov** [comment]
Thanks. That perhaps indicates strong GC/AT bias or some other QC issue. Sorry, but at the moment there is not any QC implemented in the code. It is something to be implemented.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
