### ISSUE TITLE
My bin_size is too small

### ISSUE THREAD

**Issue by CVan19** [abyzovlab/CNVnator#93]
Hi,
I have 120× whole genome sequencing data with read length around 150bp. In order to make the ratio of average RD and standard deviation 4-5, I tried many different bin_sizes. And I found that when bin_size is 60,  the ratio is 4.86709 which meets the requirement.  But 60 is too small ,is it normal?
```
File ren.root
Average RD per bin (1-22) is 53.5458 +- 11.0016 4.86709
Average RD per bin (X,Y)  is 60.7957 +- 12.5815 4.83217
```

**Comment by CVan19** [comment]
My sequencing data is from a haploid cells, may this lead to the abnormal bin_size?

**Comment by abyzov** [comment]
This is normal because you have high coverage. Making bin size larger is OK, but making smaller will make segmentation unstable.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
