### ISSUE TITLE
Does CNVnator work with a small region?

### ISSUE THREAD

**Issue by GangLiTarheel** [abyzovlab/CNVnator#99]
I am trying to call CNV for a particular region on chrom 16. Say, the lenght of that region is around 300,000 bps. Can I extract that region from each bam file, and use the bam for that region as input for CNVnator to call CNV?

In addition, is there any rule of thumbs to help me decide the bin size parameters? I am particular interested in large CNVs (maybe larger than 3kb). Need I specify the bin size to be larger than 4000?

Best,
Gang

**Comment by abyzov** [comment]
Hi,
no you should not work on a small region. The methods uses RD across whole genome or chromosome to determine normal coverage.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745

**Comment by GangLiTarheel** [comment]
Hi Alexej,

Thank you for replying me.

Do you think 5 Mb region would be big enough to run? Or it MUST run on the
whole chromosome to determine the normal coverage?
This is quite important for us since our region of interests is no more
than 5 kb.

Thank you for your time and efforts.
Best,
Gang

**Comment by abyzov** [comment]
To get better stats I would recommend to run on entire chromosome.
You may also consider genotyping the region in addition or instead of calling CNVs.

Alexej Abyzov, Ph.D.
Senior Associate Consultant,
Assistant Professor of Biomedical Informatics,
Department of Health Sciences Research,
Center for Individualized Medicine, Mayo Clinic
-----------------------------
Mayo Clinic, Harwick 3-12
200 1st street SW, Rochester, MN 55905
www.abyzovlab.org<http://www.abyzovlab.org>
tel: +1-(507)-538-0978
fax: +1-(507)-284-0745
